programa{
    funcao inicio() {
        inteiro opcao
        escreva("Escolha (1-3)")
        leia(opcao) {

            
            caso 1:
            escreva("Cadrastar usuario")
            pare
            caso 2:
            escreva("Lista Usuarios")
            pare
            caso 3:
            escreva("Sair do sistema")
            parecaso contrario:
            escreva("Opção invalida")
        }
    }
}